#配置数据库
spring:  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#配置mybatis
mybatis:
   mapper-locations: classpath:mapper/*.xml
   type-aliases-package: edu.swjtuhc.demo.mapper



  
    